### ISSUE TITLE
Implement `hc setup` subcommand to complete installation of Hipcheck

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#103]
Per RFD 002, the goal for the new setup process is that you install just the Hipcheck binary (ideally, pre-built) and then run `hc setup` to complete the setup process. This command should basically do what the current `install.sh` script does today: copy config files and script files to the proper location, and then direct the user to set up the relevant environment variables.

**Comment by j-lanson** [comment]
`install.sh` copies files from the `config` folder in the repo. Will the Hipcheck binary be distributed with this folder or should `hc setup` pull the folder from GitHub?
