### ISSUE TITLE
Update Docker deploy to include an overview and tags

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#148]
Right now the deployment page for our Docker builds is sparse and not particularly helpful. There should be an overview which links to the project `README.md` at the very least, and tags to aid in discovering the images.

https://hub.docker.com/r/mitre/hipcheck

**Comment by patrickjcasey** [comment]
I do not have permission to assign this issue to myself, but I have started to work on it!

**Comment by alilleybrinker** [comment]
@patrickjcasey you should have permissions now! I've added you to the @mitre/hipcheck-maintainers team :smile:
