### ISSUE TITLE
Write an explainer for Hipcheck's values as a project

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#17]
Hipcheck has some values which are central to _why_ it exists and help inform its features, and which are also important for differentiating it from other tools in the software supply chain space. Once we've gotten Hipcheck's documentation site up and running (see #5), we should document the values of the Hipcheck project. These include:

* __Security-Focused__: Hipcheck's analyses are solely intended to be focused on security-relevant practices and identifiable risks associated with a project, and _not_ analyses which identify non-security-relevant best practices.
* __Information, Not Scores__: We do not ever want Hipcheck's scores to become a metric which users of open source software use to bully maintainers into compliance. Open source maintainers are doing often thankless work with limited resources in both time and funding, and we should always focus on how Hipcheck can empower them, not make their job harder by creating a metric to drive up.
* __Configurable__: Security _is_ context-sensitive. Different risks may be weighted differently by different users, or even be show-stoppers for some. The nature of what is concerning may change depending on the context. We are making a security tool, and while we _can_ and _should_ have recommended defaults, we should also empower users to tailor the tool to their needs, so it can be adaptable to their systems and their security requirements, rather than them adapting to our limitations.

**Comment by sei-shissam** [comment]
Not 100% sure this is the right place to "add" to this enhancement and perhaps another open ticket may be better to address this. But here goes.

for my use case, I use hipcheck to perform analysis on a given GitHub site (thank you). And the results in json are nearly exactly what I need. However, as those results are pulled from the json, there are ancillary explanation that I was to include in that extraction for my use which are better "scraped" from the text output from hipcheck.

for example: using the ```identity``` analysis
- in the json, I get:
`  {
      "analysis": "Identity",
      "value": 0.9379715004191115,
      "threshold": 0.2
    },
`
- in the text version I get:
`- commits too often applied by the author 93.80% of commits merged by author, 20.00% permitted`

for a report writer, the text is great, but for analyzing scores (on a backend) the json is great. My use case is both... hence I need to run hipcheck twice on the same site to get all I need for the use case.

Perhaps the json could look like:
`  {
      "analysis": "Identity",
      "value": 0.9379715004191115,
      "threshold": 0.2,
      "text": "commits too often applied by the author 93.80% of commits merged by author, 20.00% permitted"
    },
`
Thanks for the consideration

**Comment by alilleybrinker** [comment]
> Not 100% sure this is the right place to "add" to this enhancement and perhaps another open ticket may be better to address this. But here goes.
> 
> for my use case, I use hipcheck to perform analysis on a given GitHub site (thank you). And the results in json are nearly exactly what I need. However, as those results are pulled from the json, there are ancillary explanation that I was to include in that extraction for my use which are better "scraped" from the text output from hipcheck.
> 
> for example: using the `identity` analysis
> 
> * in the json, I get:
>   ` { "analysis": "Identity", "value": 0.9379715004191115, "threshold": 0.2 },`
> * in the text version I get:
>   `- commits too often applied by the author 93.80% of commits merged by author, 20.00% permitted`
> 
> for a report writer, the text is great, but for analyzing scores (on a backend) the json is great. My use case is both... hence I need to run hipcheck twice on the same site to get all I need for the use case.
> 
> Perhaps the json could look like: ` { "analysis": "Identity", "value": 0.9379715004191115, "threshold": 0.2, "text": "commits too often applied by the author 93.80% of commits merged by author, 20.00% permitted" },` Thanks for the consideration

Thanks Scott! We have an open issue (#18) that will be the first step toward addressing the inconsistency you've identified! Establishing parity between the human-readable and JSON formats is one of our goals for the year!
