### ISSUE TITLE
Document what a "concerning" contributer means 

### ISSUE THREAD

**Issue by japharl** [mitre/hipcheck#211]
If possible, please define what a "concerning" contributor test means.  Eg.  

```
          Failing
                - has concerning contributors
                  733 found, 0 permitted
                  Both - affiliation count 2

```

Which contributors / why were they (all) flagged?  What affiliations were concerning?

**Comment by alilleybrinker** [comment]
Thanks for asking! This is documented on the Hipcheck website as part of the [Complete Guide to Hipcheck](https://mitre.github.io/hipcheck/docs/guide/analyses/#affiliation).
