### ISSUE TITLE
Failed to load configuration.

### ISSUE THREAD

**Issue by milosgajdos** [mitre/hipcheck#214]
I am following the quick start guide https://mitre.github.io/hipcheck/docs/quickstart/ and on the first run I get an error telling me I am missing a config file:

```shell
./hc check https://github.com/mitre/hipcheck
        Analyzing https://github.com/mitre/hipcheck
      In Progress loading configuration and data files
            Error Failed to load configuration. Please make sure the config files are in the config directory.
                  '/Users/<REDACTED_USERNAME>/Library/Application Support/hipcheck/config/Hipcheck.toml' not found at current directory
```

Version:
```shell
./hc --version
Hipcheck 3.4.0
```

**Comment by alilleybrinker** [comment]
Hi @milosgajdos, did you run `hc setup` before trying to run `hc check`? `hc setup` ensures you have the default configuration and data files necessary to run Hipcheck.

Also, can you share the output of `hc ready`?

I do see that neither the install instructions nor quickstart guide say to run `hc setup` first. I'll open an issue for that.

We could also make the error message here suggest running `hc setup`.

**Comment by milosgajdos** [comment]
I haven't actually. The quickstart doesnt mention `hc setup` 🤔 maybe worth mentioning it there 😄

**Comment by milosgajdos** [comment]
Ok yeah, that did the trick! Thanks @alilleybrinker 

I still think it's worth mentioning the setup step in the quickstart for simpletons like myself 😄 

Closing.

**Comment by alilleybrinker** [comment]
Yeah I've made issues to update the docs, and to improve the error message to suggest it as well. This is totally on us to make sure to tell people!
