### ISSUE TITLE
Push images to Docker Hub

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#22]
Can coordinate with @Amndeep7. We have a `Containerfile` but don't currently push any prebuilt images to Dockerhub. Ideally we'd do this with each new version in an automated fashion. The SAF folks control the MITRE namespace on Docker Hub so we'll coordinate with them.

- [ ] Talk with Amndeep about how to authenticate for publication to the MITRE Docker Hub namespace.
- [ ] Investigate GitHub Actions for publishing new images when new release version tags are pushed to Github.

**Comment by j-lanson** [comment]
This mostly involves getting a (DockerHub username, DockerHub token) pair to store as secrets in our repo. There is already a good foundation of GH workflow `.yml` files to work off of for implementing the desired behavior.

@alilleybrinker, Amndeep says the SAF team has a limited number of seats on their DockerHub org. To be resource-efficient, we could have an existing SAF team member generate a token and use their account for our GitHub secrets. Or if this isn't appropriate in your view, we could set up a team member such as yourself with their own account.

**Comment by alilleybrinker** [comment]
Let me talk with Alec about this. I don't think we'll have a conclusion today.
