### ISSUE TITLE
hipcheck does not work with scopes

### ISSUE THREAD

**Issue by msbannert** [mitre/hipcheck#235]
HipCheck 3.4.0 running on windows 10 /  powershell:

packages which are scoped cannot be analyzed.
Example:
https://registry.npmjs.org/@types/ua-parser-js

PS D:\hipcheck> hc check "@types/ua-parser-js" -t npm
        Analyzing @types/ua-parser
             Done loading configuration and data files
error: no repository given for npm package

**Comment by alilleybrinker** [comment]
Thanks for reporting this! We'll let you know when it's fixed 😄

**Comment by alilleybrinker** [comment]
The fix has been merged, and we're planning to release Hipcheck 3.5.0 this week on Thursday, which will include the fix.
