### ISSUE TITLE
Update site to announce 3.5.0 release

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#253]
Right now it still reflects the 3.4.0 release.

**Comment by patrickjcasey** [comment]
I was going to tackle this small issue, but it seems as if the `site/config.toml` has already been updated and the website seems to already be showing the `3.5.0` release

![image](https://github.com/user-attachments/assets/195d3e96-1601-49ab-9170-839a585b1f9a)

**Comment by patrickjcasey** [comment]
closed by https://github.com/mitre/hipcheck/pull/263
