### ISSUE TITLE
Add a command to view scoring breakdown

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#28]
Right now you can configure Hipcheck to produce scores based on weights for different analyses, but you can't really see the calculated percentages for each leaf of the scoring tree, which makes it difficult to understand how scores are actually calculated. It would be really great if there were a command to see this broken down, and ideally also a way to see it in the output (both human and machine readable) when you run analyses.

- [x]  Define new `AnalysisReport` struct to abstract value/threshold predicate and move into Pass/Fail enumeration. 
- [x] Update analyses to use new `AnalysisReport`. 
- [x] Move decision to run/skip analysis out of `X_analysis()` functions and into the HipCheck core
- [x] Change `AnalysisResults` to be a `HashMap` that maps analysis labels to updated `AnalysisReport` objects
- [x] Create `WeightTree` object and provider for getting a normalized version based on config
- [x] Update scoring to combine updated `AnalysisResults` map + normalized `WeightTree` to produce a `ScoreTree`
- [x] Update errored analyses to act as `Fail` for the purpose of score calculation, and notify user of errors
- [ ] Add ability to print what percentage of the total score each analysis accounted for by walking the `ScoreTree`

**Comment by alilleybrinker** [comment]
Hey @vcfxb, with Julian out for a bit, think you could bring this over the finish line? With the introduction of the weight tree abstraction we should have all the underlying mechanisms in place to add the new subcommand. I'm happy to sync to discuss what's left for this.

**Comment by vcfxb** [comment]
Looking into this now -- I think it would probably be good to sync up and discuss what still needs to be done sometime @alilleybrinker
