### ISSUE TITLE
Write RFD assessing opportunities for improving the release process

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#393]
Make sure it covers:

- Better Docker image deploys with `cargo-dist`
- Windows codesigning
- macOS codesigning
- GitHub Attestations (is this SLSA?)

**Comment by j-lanson** [comment]
@alilleybrinker just checking, is this closed by #430 ?

**Comment by alilleybrinker** [comment]
Ah, I suppose it is!
