### ISSUE TITLE
🛤️ Tracking Issue - Convert existing standard Hipcheck metrics/analyses to plugins

### ISSUE THREAD

**Issue by mchernicoff** [mitre/hipcheck#470]
Hipcheck currently has an original, "core" set of metrics and analyses from prior to the addition of the plugin system. At the moment, they are hardcoded into Hipcheck's base code. We should convert each of these to a plugin to run under the new system.

The core metrics analyses that should become plugins are:

- [x] #485
- [x] #499
- [x] #526
- [x] #520
- [x] #489
- [x] #534
- [x] #518
- [x] #482
- [x] #537

But these analyses depend on broader data sources that will also need their own plugins (or possibly multiple plugins for each):

- [x] #472
- [x] #474 
- [x] #480

Validation of plugins written without itegration testing:
- [x] #539
- [x] #559
- [x] #545
- [x] #549
- [x] #551
- [x] #547

Deleting code from `hipcheck/src` associated with legacy analyses:
- [x] #623
- [x] #625
- [x] #631
- [x] #632
- [x] #640
- [x] #641
- [x] #642
- [x] Delete legacy code for git plugin
- [x] Delete legacy code for github API plugin
- [x] #659
- [x] #660

**Comment by j-lanson** [comment]
Closing as complete 🥳
