### ISSUE TITLE
Interaction with RUST_LOG and our commandline printing

### ISSUE THREAD

**Issue by j-lanson** [mitre/hipcheck#504]
Hipcheck does some stuff to control writing to the commandline, and it seems that when I run with `RUST_LOG=debug` I don't see any `log::debug!` prints which I would like to be displayed. Diagnose why logging prints don't show up and fix

**Comment by alilleybrinker** [comment]
Oh, we reassign the environment variable to HC_LOG instead of RUST_LOG
