### ISSUE TITLE
Unclear What Plugin Passed/Failed

### ISSUE THREAD

**Issue by patrickjcasey** [mitre/hipcheck#554]
**Describe the bug**
When running the `fuzz` and `binary` plugins, The resulting output is to indicate what analysis pass/failed, which is confusing

**To Reproduce**
Steps to reproduce the behavior.

I used this minimal config to reproduce the issue: 

```
plugins {
    plugin "mitre/binary" version="0.1.0" manifest="./plugins/binary/plugin.kdl"
    plugin "mitre/fuzz" version="0.1.0" manifest="./plugins/fuzz/plugin.kdl"
}
patch {
	plugin "mitre/github_api" {
		api-token-var "HC_GITHUB_TOKEN"
	}
}
analyze {
    investigate policy="(gt 0.5 $)"

     category "practices" {
        analysis "mitre/activity" policy="(lte $ 52)" weight=3
        analysis "mitre/binary" {
			binary-file "./config/Binary.toml"
			binary-file-threshold 0
		}
        analysis "mitre/fuzz" policy="(eq #t $)"
    }
}

```
I ran this command from the root of the `hipcheck` repo:
`cargo build --workspace;  ./target/debug/hc check --policy ./Hipcheck.kdl-testing https://github.com/mitre/hipcheck.git`

**Expected behavior**
It should show the name of the plugin in the results, or somehow make it clear which plugin is failing and which plugin is succeeding.

**Screenshots**

Without examining the policy file, it is hard to determine which policy `satisfied associated policy` and which plugin `failed to meet policy`

![image](https://github.com/user-attachments/assets/cf8c82cd-bdbe-4ea1-8ddb-729e5bb3661f)

**Desktop (please complete the following information):**
 - Operating System: macOS Sonoma 14.7
 - Hipcheck Version: testing was as of commit hash `56dd7a76b837e52236e47e2d3db3caec98962767`

**Comment by j-lanson** [comment]
@patrickjcasey has this been fixed by recent PRs?

**Comment by patrickjcasey** [comment]
recent PRs seen to have fixed this! closing this issue
