### ISSUE TITLE
`git` parser can't handle patchless diff

### ISSUE THREAD

**Issue by j-lanson** [mitre/hipcheck#574]
In one of the commits in this repo, there is a diff that looks like this:
```
diff --git a/hipcheck/src/analysis/session/spdx.rs b/hipcheck/src/session/spdx.rs
similarity index 100%
rename from hipcheck/src/analysis/session/spdx.rs
rename to hipcheck/src/session/spdx.rs
```
This is all metadata, and our parser expects that afterwards there will be a line starting with `@@` to denote where the diff "content" occurs. However, this is a rename-only change, so there is no content to emit.

**Comment by alilleybrinker** [comment]
@j-lanson looks like this test case passes with the closing `\n` added in.
