### ISSUE TITLE
mitre/typo analysis error: unspecified error from plugin

### ISSUE THREAD

**Issue by bmarr-mitre** [mitre/hipcheck#602]
If I run hipcheck on  https://github.com/coreybutler/nvm-windows, I get a message:

_> Errored
>                    ? mitre/typo analysis error: unspecified error from plugin_

I ran this on my Windows 11 desktop on main.

![image](https://github.com/user-attachments/assets/f6062233-fcfa-47b9-ace8-dcd1b42ccffb)
![image](https://github.com/user-attachments/assets/66804401-99a3-4a8d-a041-505edf737e74)

  

Note, I get the same behavior with running on this repo:
 .\target\debug\hc check  --policy config/Hipcheck.kdl https://github.com/coreybutler/fenix

**Comment by alilleybrinker** [comment]
The error reporting here needs to be better, but this is an expected error. Typosquatting analysis currently only supports NPM packages. It looks like the repo in question here is a Go codebase.
