### ISSUE TITLE
Update README contract information

### ISSUE THREAD

**Issue by jordangov** [mitre/hipcheck#64]
The README.md file has a "Public Release" section at the end which identifies two government contracts that this work was completed under. I'm excited to see development picking back up! Can the core team please update the documentation to include current contract information if possible? If that's not possible, perhaps rewording that section to clearly identify what work (time period) was done under which contract?

**Comment by jordangov** [comment]
<3

**Comment by alilleybrinker** [comment]
Sorry it took so long!
